services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shorterlink
      POSTGRES_USER: shorterlink
      POSTGRES_PASSWORD: shorterlink_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shorterlink"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
